
version: '3'

services:
    postgres:
        image: postgres:16.0
        environment:
            POSTGRES_DB: wallet
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Pass1234
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"

volumes:
    pgdata:
